examples/allowlist/README.md
examples/apikey/README.md
examples/appservice/README.md
examples/backup/create_backups/README.md
examples/backup/list_backups/README.md
examples/backup_schedule/README.md
examples/bucket/README.md
examples/cluster/README.md
examples/database_credential/README.md
examples/project/README.md
examples/user/README.md

* AV-69477
<details open>
</details>

[AV-69447] Updated Readme for IMPORT

---

docs/index.md

* AV-64392
<details open>
</details>

Documentation format tweaks

---

examples/cluster/variables.tf
examples/getting_started/variables.tf

* AV-70854
<details open>
Validations added to the jira ticket - https://couchbasecloud.atlassian.net/browse/AV-70854
</details>

[AV-70854] Fixed optional fields during cluster creation | Azure & GCP

---

internal/resources/acceptance_tests/allowlist_acceptance_test.go
internal/resources/acceptance_tests/cluster_acceptance_test.go
internal/resources/acceptance_tests/database_credential_acceptance_test.go

* AV-XXXXX
<details open>
</details>

Fix the cluster version as 7.1 is not supported

---

CONTRIBUTING.md

* AV-72750
Improves the markdown document contributing.md. Aims to be able to get developers running the provider quicker and easier. Significant knowledge gaps were present in the document before this change. 
<details open>
I have worked through the document and checked that we can reach deployment with all the information provided in the document. 
</details>

AV-72750 Reformat contributing.md

---

internal/resources/acceptance_tests/azure_storage_auto_expansion_acceptance_test.go

* AV-71279
This PR is to add the acceptance tests for azure storage auto expansion feature.
<details open>
http://qe-jenkins1.sc.couchbase.com/job/terraform-test/199/console
http://qe-jenkins1.sc.couchbase.com/job/terraform-test/197/console
</details>

Adding Azure storage auto expansion accpetance tests

---

.github/CODEOWNERS

* AV-74846
Codeowner file change to require both QE and terraform team reviews instead of having it only be QE
<details open>
</details>

AV-74846 Updare codeowners to require both teams reviews

---

Makefile

* [AV-74974](https://couchbasecloud.atlassian.net/browse/AV-74974)
<details open>
</details>

AV-74974 goimports

---

examples/appservice/README.md
examples/backup/create_backups/README.md
examples/backup/list_backups/README.md

* AV-75060
Updating example readmes
<details open>
</details>

Update example readmes

---

.golangci.yml

* [AV-74940 ](https://couchbasecloud.atlassian.net/browse/AV-74940)
Adding the goimports linter to catch imports that are not in the correct order. 
<details open>
</details>

AV-74940 Adding the goimports to the linters run

---

internal/resources/bucket.go
internal/resources/database_credential.go
internal/resources/project.go

* [AV-74785](https://couchbasecloud.atlassian.net/browse/AV-74785)
Updating incorrect error messages
<details open>
</details>

AV-74785 Updated incorrect error messages

---

docs/index.md
examples/bucket/collections/README.md
examples/cluster_onoff_ondemand/README.md
examples/cluster_onoff_schedule/README.md
internal/errors/errors.go

* AV-76040
<details open>
</details>

AV-76040- Terraform reformatting

---

examples/getting_started/README.md
examples/getting_started/audit_logs.tf
examples/getting_started/terraform.template.tfvars
examples/getting_started/variables.tf

* [AV-76547](https://couchbasecloud.atlassian.net/browse/AV-76547)
<details open>
</details>

update getting started for audit log settings

---

.github_changelog_generator
CHANGELOG.md

* [AV-76553](https://couchbasecloud.atlassian.net/browse/AV-76553)
<details open>
</details>

[AV-76553] Added Changelog for v1.2.0

---

docs/guides/1.2.1-upgrade-guide.md
docs/resources/audit_log_export.md
go.mod
go.sum

* AV-77843
<details open>
</details>

[AV-77843] Prepare Release Documentation for v1.2.1

---

.github_changelog_generator
CHANGELOG.md

* AV-77843
<details open>
</details>

Changelog added for v1.2.1 release

---

docs/guides/1.2.1-upgrade-guide.md

* AV-78197
<details open>
</details>

[AV-78197] Made the fix for version v1.2.1 in the release guide.

---

CONTRIBUTING.md

* AV-83061
<details open>
</details>

AV-83061 - Updating contributing.md with windows steps

---

examples/cluster/README.md
examples/getting_started/README.md
internal/api/cluster/cluster.go
internal/datasources/cluster_schema.go
internal/resources/acceptance_tests/cluster_acceptance_test.go
internal/resources/cluster.go
internal/resources/cluster_schema.go
internal/schema/cluster.go

* [AV-85334](https://jira.issues.couchbase.com/browse/AV-85334)
Adding `connectionString` to cluster response as per requirement.
<details open>
Added the testing in the AV.
</details>

AV-85334 Adding connection string in Get cluster

---

examples/getting_started/private_endpoint_service.tf

* [AV-85326](https://jira.issues.couchbase.com/browse/AV-85326)
Fix private endpoint service getting started example.
<details open>
test result is too large to fit here !
</details>

AV-85326 | fix PES example

---

.github/workflows/release.yml

* AV-87193
<details open>
</details>

Updating the version for gorunner

---

.github/workflows/release.yml

* AV-87193
<details open>
</details>

AV-87139 fix gorunner version

---

.github/workflows/release.yml
.goreleaser.yml

* AV-87139
<details open>
</details>

Av 87139 fix gorunner version

---

examples/getting_started/README.md
examples/getting_started/gsi.tf
examples/getting_started/terraform.template.tfvars
examples/getting_started/variables.tf
examples/gsi/deferred/create_indexes.tf

* [AV-92775](https://jira.issues.couchbase.com/browse/AV-92775)
a.  correct index json file name in GSI deferred example
b.  in getting started, set auth token using env var
c.  update getting started gsi example to create non deferred secondary index
<details open>
cannot test doc change
</details>
Since this is doc enhancement these checks don't apply:
-  I have added tests that prove my fix is effective or that my feature works per HashiCorp requirements
- I have made sure that no schema field is marked with both requiresReplace and computed

AV-92775 | doc improvements

---

CHANGELOG.md
docs/guides/1.4.1-upgrade-guide.md

* AV-93122
Added Changelog for provider V1.4.1
<details open>
</details>

Added changelog for provider version V1.4.1

---

.github/workflows/acceptance-tests.yml
.github/workflows/lint.yml
.github/workflows/release.yml
.github/workflows/unit-tests.yml
internal/resources/acceptance_tests/cluster_acceptance_test.go

* AV-97063
* AV-97068
Tie down the versions for golangci-lint and ubuntu and fix the acceptance tests.
Tested via Github actions
<details open>
</details>

[AV-97063] Tie down the versions for golangci-lint and ubuntu

---

acceptance_tests/setup_test.go

* AV-97308
clean up common cluster and project even on setup failure.  for example, if common project get created but cluster does not, the common project should get destroyed.
<details open>
```
2025/03/05 15:50:15 project created
2025/03/05 15:50:15 {"code":4010,"hint":"Please ensure that the CIDR range is unique within this organisation.","httpStatusCode":422,"message":"Unable to process request. Please ensure that the CIDR range is unique within this organisation"}
2025/03/05 15:50:15 project destroyed
FAIL    github.com/couchbasecloud/terraform-provider-couchbase-capella/acceptance_tests 0.553s
FAIL
```
</details>

AV-97308 | properly clean up resources

---

examples/backup/create_backups/README.md

* [AV-97194](https://jira.issues.couchbase.com/browse/AV-97194)
Updates the backup example to clarify that buckets are being backed up
<details open>
cannot test doc update
</details>

AV-97194 | update doc

---

internal/resources/network_peer.go

* [AV-99812](https://jira.issues.couchbase.com/browse/AV-99812)
`provider_type` is not set in `retrieveNetworkPeer` which causes terraform to replace the resource
<details open>
// create resource for the first time
```
terraform apply -auto-approve
╷
│ 
│ 
╵
Terraform used the selected providers to generate the following execution plan. Resource actions are …
```

AV-99812 | set provider type

---

examples/data-sources/couchbase-capella_audit_log_export/data-source.tf
examples/resources/couchbase-capella_audit_log_export/import.sh
examples/resources/couchbase-capella_audit_log_export/resource.tf
internal/datasources/audit_log_export.go
internal/resources/audit_log_export_schema.go

* AV-100861
1. Add documentation for audit log export resource and datasource to be visible as examples in the docs
<details open>
</details>

AV-100861 - Audit log export docs

---

examples/data-sources/couchbase-capella_aws_private_endpoint_command/data-source.tf
examples/data-sources/couchbase-capella_azure_private_endpoint_command/data-source.tf
internal/datasources/aws_private_endpoint_command.go
internal/datasources/azure_private_endpoint_command.go

* AV-100858
1. Add documentation for private endpoints commands datasources to be visible as examples in the docs
<details open>
</details>

AV-100858 - Private endpoint command docs

---

examples/data-sources/couchbase-capella_private_endpoints/data-source.tf
examples/resources/couchbase-capella_private_endpoints/import.sh
examples/resources/couchbase-capella_private_endpoints/resource.tf
internal/datasources/private_endpoints.go
internal/resources/private_endpoints.go

* AV-100860
1. Add documentation for private endpoints resource and datasource to be visible as examples in the docs
<details open>
</details>

AV-100860 -  Private endpoints docs

---

examples/data-sources/couchbase-capella_organization/data-source.tf
internal/datasources/organization.go

* AV-100857
1. Add documentation for organizations datasources to be visible as examples in the docs
<details open>
</details>

AV-100857- Organization docs

---

examples/data-sources/couchbase-capella_events/data-source.tf
internal/datasources/attributes.go
internal/datasources/events_schema.go

* [AV-100871](https://jira.issues.couchbase.com/browse/AV-100871)
1. Add datasource documentation for events datasource to be visible as examples in the docs
<details open>
</details>

[AV-100871] feat: Added docs for events.

---

examples/resources/couchbase-capella_flush/resource.tf
internal/resources/flush_bucket_schema.go

* [AV-100870](https://jira.issues.couchbase.com/browse/AV-100870)
1. Add resource documentation for flush resource to be visible as examples in the docs
<details open>
<summary>Resource</summary>
</details>

[AV-100870] feat: Added docs for flush bucket.

---

examples/data-sources/couchbase-capella_event/data-source.tf
internal/datasources/event_schema.go

* [AV-100872](https://jira.issues.couchbase.com/browse/AV-100872)
1. Add datasource documentation for event datasource to be visible as examples in the docs
<details open>
</details>

[AV-100872] feat: Added docs for event.

---

examples/data-sources/couchbase-capella_database_credential/data-source.tf
examples/resources/couchbase-capella_database_credential/import.sh
examples/resources/couchbase-capella_database_credential/resource.tf
internal/datasources/database_credentials.go
internal/resources/database_credential_schema.go

* [AV-100873](https://jira.issues.couchbase.com/browse/AV-100873)
1. Add resource documentation for database credential resource to be visible as examples in the docs
<details open>
<summary>Resource</summary>
</details>
<details open>
</details>

[AV-100873] feat: Added docs for database credential.

---

examples/data-sources/couchbase-capella_apikey/data-source.tf
examples/resources/couchbase-capella_apikey/import.sh
examples/resources/couchbase-capella_apikey/resource.tf
internal/datasources/apikeys.go
internal/resources/apikey_schema.go

* [AV-100875](https://jira.issues.couchbase.com/browse/AV-100875)
1. Add resource documentation for apikey resource to be visible as examples in the docs
<details open>
<summary>Resource</summary>
</details>
<details open>
</details>

[AV-100875] feat: Added docs for apikey.

---

examples/data-sources/couchbase-capella_project_events/data-source.tf
internal/datasources/project_events_schema.go

* [AV-100867](https://jira.issues.couchbase.com/browse/AV-100867)
1. Add datasource documentation for project events datasource to be visible as examples in the docs
Description for Event Data, hrefs and cursor have been added with events PR.
<details open>
</details>

[AV-100867] feat: Added docs for project events.

---

examples/data-sources/couchbase-capella_project_event/data-source.tf
internal/datasources/project_event_schema.go

* [AV-100868](https://jira.issues.couchbase.com/browse/AV-100868)
1. Add datasource documentation for project event datasource to be visible as examples in the docs
<details open>
</details>

[AV-100868] feat: Added docs for project event.

---

examples/data-sources/couchbase-capella_free_tier_clusters/data-source.tf
examples/free_tier_cluster/list_free_tier_clusters.tff
examples/resources/couchbase-capella_free_tier_cluster/import.sh
examples/resources/couchbase-capella_free_tier_cluster/resource.tf
internal/resources/free_tier_cluster_schema.go

* AV-100850
Add free-tier cluster docs
<details open>
</details>

AV-100850: Adding free-tier cluster docs

---

examples/resources/couchbase-capella_free_tier_cluster_on_off/import.sh
examples/resources/couchbase-capella_free_tier_cluster_on_off/resource.tf
internal/resources/free_tier_cluster_on_off_schema.go

* AV-100851
adding free tier on/off docs
<details open>
</details>

AV-100851: Adding free tier on/off docs

---

examples/data-sources/couchbase-capella_certificate/data-source.tf
internal/datasources/certificate.go

* AV-100879
Adding certificate data source docs
<details open>
</details>

AV-100879 : Adding certificate docs

---

examples/resources/couchbase-capella_app_service_onoff_ondemand/import.sh
examples/resources/couchbase-capella_app_service_onoff_ondemand/resource.tf
internal/resources/appservice_onoff_schema.go

* AV-100880
Adding app services on/off docs
<details open>
</details>

AV-100880: Adding app service on/off docs

---

examples/resources/couchbase-capella_backup_schedule/import.sh
examples/resources/couchbase-capella_backup_schedule/resource.tf
internal/resources/backup_schedule_schema.go

* AV-100878
This PR adds backup schedule resource docs 
<details open>
</details>

AV-100878: Adding backup schedule docs

---

.github/pull_request_template.md
.github/workflows/label-pr.yml

* AV-101826
Testing adding PR labels automatically as per the selected Type of change. For this PR, I am selecting - New Feature and Documentation, accordingly the labels should be added to the PR through Github actions.
<details open>
</details>

AV-101826 - Automate adding PR labels

---

examples/data-sources/couchbase-capella_collections/data-source.tf
examples/data-sources/couchbase-capella_scopes/data-source.tf
examples/resources/couchbase-capella_collection/import.sh
examples/resources/couchbase-capella_collection/resource.tf
examples/resources/couchbase-capella_scope/import.sh
examples/resources/couchbase-capella_scope/resource.tf
internal/datasources/collections.go
internal/resources/collection_schema.go
internal/resources/scope_schema.go

* AV-102119
Examples and docs for scopes and collections.
Collections -
Scopes-
<details open>
</details>

AV-102119 - Scopes and Collections docs

---

internal/datasources/apikeys.go
internal/datasources/cluster_schema.go
internal/datasources/database_credentials.go
internal/datasources/organization.go
internal/datasources/private_endpoint_service.go
internal/datasources/private_endpoints.go
internal/datasources/project_event_schema.go
internal/datasources/project_events_schema.go
internal/resources/apikey_schema.go
internal/resources/appservice_schema.go
internal/resources/audit_log_export_schema.go
internal/resources/audit_log_settings_schema.go
internal/resources/backup_schema.go
internal/resources/cluster_onoff_schema.go
internal/resources/cluster_schema.go
internal/resources/network_peer_schema.go

* AV-102211
Last few bits of additional comments for docs have been resolved in this PR.
<details open>
</details>

AV-102211 - Addressing final docs comments

---

CHANGELOG.md

* AV-101586
Changelog generated for v1.5.0.
<details open>
</details>

[AV-101586] Changelog for v1.5.0

---

Makefile
acceptance_tests/app_service.go
acceptance_tests/appservice_acceptance_test.go
acceptance_tests/cluster.go
acceptance_tests/globals.go
acceptance_tests/setup_test.go
internal/api/cluster/cloud_provider.go

* [AV-103003](https://jira.issues.couchbase.com/browse/AV-103003)
create common app services cluster which will be needed for acceptance tests
<details open>
CI/CD workflow will automatically test this
</details>

[AV-103003] Create common app service for acc tests

---

docs/guides/1.5.2-upgrade-guide.md

* AV-106890
upgrade guide for terraform release 1.5.2
<details open>
</details>

[AV-106890] Upgrade guide

---

internal/provider/provider.go
internal/resources/access_function.go
internal/resources/access_function_schema.go
internal/schema/access_function.go

* AV-104556
Add access function schema and resource stubs
<details open>
</details>

[AV-104556] Add Access function schema

---

internal/provider/provider.go
internal/resources/import_filter.go
internal/resources/import_filter_schema.go
internal/schema/import_filter.go

* AV-104546
Add import filter schema and add it to resources in provider.go
<details open>
</details>

[AV-104546] Add import filter schema

---

internal/resources/bucket.go
internal/resources/bucket_schema.go

* AV-111247
provider should not set bucket defaults.  this should be set by backend.
<details open>
test validation in ticket
</details>

[AV-111247] Do not set bucket defaults in provider

---

internal/datasources/app_endpoint.go
internal/datasources/app_endpoint_schema.go
internal/datasources/app_endpoints.go
internal/datasources/app_endpoints_schema.go
internal/provider/provider.go
internal/schema/app_endpoint.go

* AV-104553
Add a datasource for a single app endpoint, _app_endpoint
Rename previous references to _app_endpoints datasource to plural app endpoints in the code to differentiate between them
Testing on ticket
<details open>
</details>

[AV-104553] Add single app endpoint datasource

---

internal/schema/app_endpoint_activation_status.go

* AV-112324
Remove null checks in `(a *AppEndpointActivationStatus) Validate()` to fix import, as those fields are already null on import and cause an error
testing on ticket
<details open>
</details>

[AV-112324] Fix activation status import
