couchbasecloud/terraform-provider-couchbase-capella

internal/resources/acceptance_tests/organization_acceptance_test.go

* AV-XXXXX
Fix jenkins error due to regex format mismatch
<details open>
TF_ACC=1 go test -timeout=300m -v ./... -run TestAccOrganizationDataSource
=== RUN   TestAccOrganizationDataSource
--- PASS: TestAccOrganizationDataSource (5.12s)
PASS
ok  	github.com/couchbasecloud/terraform-provider-couchbase-capella/internal/resources/acceptance_tests
</details>

fix format issue for regex check

---

examples/cluster/azure/README.md
examples/cluster/azure/create_cluster.tf
examples/cluster/azure/main.tf
examples/cluster/azure/terraform.template.tfvars
examples/cluster/azure/variables.tf
internal/api/cluster/node.go
internal/datasources/cluster_schema.go
internal/resources/cluster.go
internal/resources/cluster_schema.go
internal/schema/cluster.go

* [AV-71279](https://couchbasecloud.atlassian.net/browse/AV-71279)
```
make testacc
TF_ACC=1 go test -timeout=300m -v ./... -run TestAccOrganizationDataSource -run TestAccProjectResource -run TestAccCreateProjectWithReqFields -run TestAccCreateProjectOptFields -run TestAccValidProjectUpdate -run TestAccInvalidProjectResource -run TestAccDeleteProjectBeforeDestroy -run TestAccClusterResourceAzure -run TestAccClusterResourceGCP -run TestAccClusterResourceWithOnlyReqFieldAWS
?   	github.com/couchbasecloud/terraform-provider-couchbase-capella	[no test files]
?   	github.com/couchbasecloud/terraform-provider-couchbase-capella/internal/api/appservice	[no test files]
? …
```

[AV-71279] Support autoexpansion for Azure cluster resource

---

internal/resources/audit_log_export_schema.go

* [AV-77464](https://couchbasecloud.atlassian.net/browse/AV-77464)
<details open>
</details>
```
terraform apply
╷
│
│  - couchbasecloud/couchbase-capella in /Users/hiteshwalia/GolandProjects/terraform-provider-couchbase-capella/bin
│
╵
data.couchbase-capella_audit_log_export.existing_auditlogexport: Reading... …
```

[AV-77464] fix export schema

---

Makefile
internal/api/client.go

* [AV-79411](https://couchbasecloud.atlassian.net/browse/AV-79411)
Use custom user agent in HTTP header so we can identify requests from terraform.
Tested by retrieving org details from terraform.  This uses `ExecuteWithRetry`.
Validated with `tcpdump` we get custom user agent:
```
Transmission Control Protocol, Src Port: 60791, Dst Port: 8084, Seq: 1, Ack: 1, Len: 328
Hypertext Transfer Protocol
GET /v4/organizations/ffffffff-aaaa-1414-eeee-000000000000 HTTP/1.1\r\n
Host: localhost:8084\r\n
User-Agent: terraform-provider-couchbase-capella/1.2.0\r\n
Authorization: Bearer <token>\r\n
Accept-Encoding: gzip\r\n
```

AV-79411 custom user agent in HTTP header

---

internal/resources/acceptance_tests/cluster_acceptance_test.go
internal/resources/acceptance_tests/security_acceptance_tests/clusters_security_acceptance_test.go

* [AV-83067](https://couchbasecloud.atlassian.net/browse/AV-83067)
remove server version check in acceptance tests.
```
TF_ACC=1 go test -timeout=300m -v ./... -run TestAccOrganizationDataSource -run TestAccProjectResource -run TestAccCreate
ProjectWithReqFields -run TestAccCreateProjectOptFields -run TestAccValidProjectUpdate -run TestAccInvalidProjectResource -run TestAccDeleteProjectBeforeDestroy -run TestAccClusterResourceAzure -run TestAccClusterResourceGCP -run TestAccClusterResourceWithOnlyReqFieldAWS
?   	github.com/couchbasecloud/terraform-provider-couchbase-capella	[no test files]
?   	github.com/couchbasecloud/terraform-provider-couchbase-capella/internal/api/appservice	[no test files]
?   	github.com/couchbasecloud/terraform-provider-couchbase-capella/internal/api/backup	[no …
```

AV-83067 | no server version check for acceptance tests

---

examples/audit_log_export/README.md
examples/audit_log_settings/README.md
examples/getting_started/README.md
internal/resources/audit_log_export.go
internal/resources/audit_log_settings.go

* [AV-79969](https://couchbasecloud.atlassian.net/browse/AV-79969)
Currently delete returns an error.  This can be problematic.  For example, if there is an error during create the resource is marked as tainted.  If you then run terraform plan , terraform will destroy the resource.  Since delete returns an error, this will also fail.  
It is better to do a noop for delete.
// validate no error on destroy settings
```
terraform destroy
╷
│
│
│ The behavior may therefore not match any released version of the provider and applying changes may cause …
```

[AV-79969] use noop when resource is destroyed for audit logs

---

examples/database_credential/terraform.template.tfvars
examples/getting_started/audit_logs.tf
examples/getting_started/terraform.template.tfvars

* AV-83066
Updating the .tf file bugs in getting started folder. 
<details open>
Tested on DEV-
In the examples/getting_started folder-
running terraform apply -
**resources created successfully**
```
terraform apply
╷
│ 
│  - couchbasecloud/couchbase-capella in /Users/paulomee.de/go/bin
│ 
╵
data.couchbase-capella_organization.existing_organization: Reading...
couchbase-capella_project.new_project: Refreshing state... [id=ffffffff-aaaa-1414-eeee-000000000000] …
```

AV-83066 - Resolving getting started folder bugs

---

internal/resources/acceptance_tests/cluster_acceptance_test.go
internal/resources/cluster.go
internal/resources/cluster_schema.go

* [AV-84160](https://couchbasecloud.atlassian.net/browse/AV-84160)
Timezones field for clusters is optional in management API, but not in terraform. This change makes timezone field optional and throws an improved error for invalid timezones for basic support plan.
<details>
<summary>Exclude timezone for basic package</summary>
```
Terraform apply
data.couchbase-capella_clusters.existing_clusters: Reading...
data.couchbase-capella_clusters.existing_clusters: Read complete after 1s
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
+ create
Terraform will perform the following actions:
+ resource "couchbase-capella_cluster" "new_cluster" {
+ app_service_id   = (known after apply)
+ audit            = …
```

AV-84160 make cluster timezone optional

---

internal/api/cluster/cluster.go
internal/resources/acceptance_tests/cluster_acceptance_test.go
internal/resources/attributes.go
internal/resources/cluster.go
internal/resources/cluster_schema.go
internal/schema/cluster.go

* AV-86845
Revert the removal of the configuration type from the cluster resource and mark it deprecated
Warning of Deprication
╷
│ Warning: Attribute Deprecated
│
│ with couchbase-capella_cluster.new_cluster,
│ on create_cluster.tf line 14, in resource "couchbase-capella_cluster" "new_cluster":
│ 14: configuration_type = "multiNode"
│
│ Remove this attribute's configuration as it no longer is used and the attribute will be removed in the next major version of the provider.
│
│ (and one more similar warning elsewhere)
Validated relevant acceptance test
<details open>
</details>

[AV-86845] Deprecate the `configurationType` attribute in the cluster resource

---

.github_changelog_generator
CHANGELOG.md

* AV-86503
Update the changelog for the v1.3.0 release
<details open>
</details>

[AV-86503] Updated the changelog

---

internal/resources/acceptance_tests/cluster_acceptance_test.go
internal/resources/cluster.go

* AV-86105
<details open>
</details>

[AV-86105] initialized autoexpansion field with null value

---

internal/resources/acceptance_tests/audit_log_export_acceptance_test.go

* [AV-87077](https://jira.issues.couchbase.com/browse/AV-87077)
Acceptance giving false negative.  Corrected to handle computed values.
<details open>
```
TF_ACC=1 go test -timeout=20m -run TestAccAuditLogExportTestCases
raw state map[%:17 audit.%:5 audit.created_at:2024-09-20 01:07:44.068119723 +0000 UTC audit.created_by:N4hqAQZX376Vlo9kQ8mxxzPxvhVX5QCp audit.modified_at:2024-09-20 01:09:39.511170175 +0000 UTC audit.modified_by:apikey-apikey-N4hqAQZX376Vlo9kQ8mxxzPxvhVX5QCp audit.version:5 availability.%:1 availability.type:multi cloud_provider.%:3 cloud_provider.cidr:10.0.6.0/24 cloud_provider.region:us-east-1 cloud_provider.type:aws configuration_type:multiNode connection_string:cb.ss1xws4sr1d7dn.customsubdomain.nonprod-project-avengers.com …
```

AV-87077 | handle computed values in acc test

---

CHANGELOG.md
docs/guides/1.4.0-upgrade-guide.md

* AV-87721
<details open>
</details>

Updated release documentation for GSI

---

examples/getting_started/terraform.template.tfvars

* [AV-93033](https://jira.issues.couchbase.com/browse/AV-93033)
Uncommenting lines from tfvars in Getting started folder
<details open>
</details>

AV-93033 - Uncommenting from tfvars in Getting started folder

---

docs/index.md
internal/provider/provider.go
internal/schema/cluster.go

* AV-XXXXX
* Resolves #238 
Updates the provider to allow setting of the `host` and `authorisation_token` as environment variables prefixed with `CAPELLA_` and removes `authorisation_token` as a required attribute in the configuration block as it can now be provided from an environment variable
<details open>
**Example terraform code**
```hcl
terraform {
required_providers {
couchbase-capella = {
source = "couchbasecloud/couchbase-capella"
}
}
}
data "couchbase-capella_projects" "this" {
organization_id = "e5456751-XXXXXXXXXXXXXX-aecb859d7db0"
}
output "clusters_list" {
value = "Number of current projects: ${length(data.couchbase-capella_projects.this.data)}"
}
``` …

feat: Allows setting the provider host and authorisation_token via CAPELLA prefixed environment variables

---

internal/resources/gsi.go

* [AV-97053](https://jira.issues.couchbase.com/browse/AV-97053)
For primary indexes, users can give a custom name or use the default.  If using the default, provider cannot get the index name from the plan, as user did not configure it.  Instead the index name comes from the provider itself.
<details open>
```
terraform apply -auto-approve
╷
│ 
│ 
╵ …
```

AV-97053 | correctly get default primary index name

---

internal/resources/gsi.go

* AV-97306
set indexName for secondary index
<details open>
```
terraform apply
╷
│ 
│ 
╵
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
+ create
Terraform will perform the following actions:
+ resource "couchbase-capella_query_indexes" "idx" {
+ bucket_name     = …
```

AV-97306 | set indexName

---

acceptance_tests/globals.go
acceptance_tests/gsi_accpetance_test.go
internal/resources/gsi.go

* AV-97596
initialize replica to 0 only if it's not in the plan
<details open>
```
terraform apply -auto-approve
╷
│ 
│ 
╵
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
+ create
Terraform will perform the following actions:
+ resource …
```

AV-97596 | set computed value for replica correctly

---

acceptance_tests/gsi_accpetance_test.go
examples/getting_started/gsi.tf
examples/getting_started/terraform.template.tfvars
examples/getting_started/variables.tf
internal/resources/gsi.go

* [AV-102723](https://jira.issues.couchbase.com/browse/AV-102723)
When creating multiple non-deferred indexes in parallel, indexer service will create the first request it receives and retry the other indexes.  The problem is for those retried indexes, a computed attribute `num_replica` is still left with unknown value.   
```
│ Error: Provider returned invalid result object after apply
│ 
│ After the apply operation, the provider still indicated an unknown value for couchbase-capella_query_indexes.idx1.with.num_replica. All values must be known after apply, so
│ this is always a bug in the provider and should be reported in the provider's own repository. Terraform will still save the other known object values in the state.
```
Terraform client expects it to have some value after apply. …

[AV-102723] Initialize num_replica to null

---

acceptance_tests/cluster_acceptance_test.go
internal/resources/cluster.go
internal/resources/cluster_schema.go

* AV-107162
`autoexpansion` is only valid for azure.  do not allow setting this for aws/gcp.
<details open>
validation in https://jira.issues.couchbase.com/browse/AV-107162?focusedCommentId=1239520
</details>

[AV-107162] Do not allow setting autoexpansion for AWS/GCP

---

acceptance_tests/cluster_acceptance_test.go
internal/errors/errors.go
internal/resources/cluster.go
internal/resources/cluster_schema.go

* AV-107267
do not allow users to set iops on gcp clusters
<details open>
validation in https://jira.issues.couchbase.com/browse/AV-107267?focusedCommentId=1241008
</details>

[AV-107267] Restrict setting IOPS for GCP clusters

---

examples/cluster/README.md

* AV-108158
examples readme for cluster states import command is 
`terraform import couchbase-capella_cluster.new_cluster id=<cluster_id>,project_id=<project_id>,organization_id=<organization_id>`
while testing, i was getting 
```
│ Error: Error Reading Capella Cluster
│
│ Could Not Read Capella Cluster "id=brasseallenemerson,cluster_id=ffffffff-aaaa-1414-eeee-00000000000,project_id=ffffffff-aaaa-1414-eeee-00000000000organization_id=ffffffff-aaaa-1414-eeee-00000000000": failed to validate resource state: terraform import parameters did not match those expected for the resource, please check provider documentation for syntax: error parsing terraform import: terraform import parameters did not match those expected for the resource, please check provider documentation for syntax
╵
```
while …

[AV-108158] Remove cluster ID arg from import command in examples readme
